spring.application.name=jobtracker

spring.datasource.url=jdbc:postgresql://localhost:5432/jobtracker
spring.datasource.username=jobtracker
spring.datasource.password=secret
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true